browser=chrome
baseURL = https://webdriveruniversity.com/index.html
username = jaspreet
password = jaspreet
db.url=jdbc:mysql://localhost:3306/testdb
db.user=root
db.password=admin

apiBaseURL=https://demo.duendesoftware.com
tokenEndPoint=/connect/token
apiUsername =m2m
apiPassword =secret
applicationEndPoint=/api/test


OPENAI_KEY= sk-1234567890abcdefghijklmnopqrstuvwx